module ShareCloud.main {
    requires com.fasterxml.jackson.databind;
    //requires json.patch;
    requires org.mongodb.bson;
    requires org.mongodb.driver.core;
    requires org.mongodb.driver.sync.client;
    requires spring.beans;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires spring.context;
    requires spring.data.commons;
    requires spring.data.mongodb;
    requires spring.web;
    requires spring.webflux;
    requires spring.core;
    requires spring.tx;

    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires spring.security.crypto;
    requires spring.security.core;
    requires spring.security.web;
    requires spring.security.config;
    requires spring.webmvc;
    requires jjwt.api;
    requires jakarta.persistence;
    requires spring.data.redis;
    requires java.management;
    requires spring.data.jpa;
    requires org.apache.tomcat.embed.core;
    requires spring.hateoas;
    requires javafx.graphics;
    requires java.net.http;
    requires org.json;
    requires spring.boot.actuator;
    requires java.desktop;
    requires jdk.xml.dom;
    requires ShareCloud.main;
    requires com.fasterxml.jackson.annotation;
    //requires ShareCloud.main;

    opens gal.usc.etse.sharecloud.client to javafx.fxml;
    opens gal.usc.etse.sharecloud.client.gui_controller to javafx.fxml;
    //opens gal.usc.etse.sharecloud.server.configuration to spring.core, spring.beans;
    //exports gal.usc.etse.sharecloud.server.configuration;
    //opens gal.usc.etse.sharecloud.server.repository to spring.core, spring.beans;
    //exports gal.usc.etse.sharecloud.server.repository;
    opens gal.usc.etse.sharecloud.server.configuration;
    opens gal.usc.etse.sharecloud.server.controller;
    opens gal.usc.etse.sharecloud.server.exception;
    opens gal.usc.etse.sharecloud.server.filter;
    opens gal.usc.etse.sharecloud.server.model;
    opens gal.usc.etse.sharecloud.server.repository;
    opens gal.usc.etse.sharecloud.server.service;
    exports gal.usc.etse.sharecloud.server;
    opens gal.usc.etse.sharecloud.server.model.entity;
    opens gal.usc.etse.sharecloud.client.clientModel;
    exports gal.usc.etse.sharecloud.client;

}